package cc.models.controller;

import cc.models.dto.ResponseModel;
import io.github.flashvayne.chatgpt.dto.chat.MultiChatMessage;
import io.github.flashvayne.chatgpt.service.ChatgptService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.CollectionUtils;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.util.*;

@Slf4j
@CrossOrigin
@RestController
public class Controller {
    @Autowired
    private ChatgptService chatgptService;

    // Recieves a conversation between a bot and a user, and responds with according information generated by the GPT model
    @PostMapping("/multi/send")
    public ResponseModel<String> multiSend(HttpServletRequest request, @RequestBody List<MultiChatMessage> messages) {
        String requestId = UUID.randomUUID().toString();
        log.info("requestId {}, ip {}, send messages : {}", requestId, request.getRemoteHost(), messages.toString());
        if (CollectionUtils.isEmpty(messages)) {
            return ResponseModel.fail("messages can not be empty");
        }
        String responseMessage = chatgptService.multiChat(messages);
        log.info("requestId {}, ip {}, get a reply : {}", requestId, request.getRemoteHost(), responseMessage);
        return ResponseModel.success(responseMessage);

        // return ResponseModel.success("Here are some tips and plant suggestions to consider: Start small: If you're a beginner gardener and don't have a lot of space or time, it's best to start small with just a few plants. You can always expand your garden later once you gain more experience. Choose the right location: Plants need sunlight, so make sure you choose a location that gets at least 6 hours of direct sunlight per day. If you don't have a sunny spot, consider growing plants that do well in partial shade. Pick the right soil: Soil quality is important for plant growth, so choose a good quality potting mix or amend your existing soil with compost or other organic matter. Water regularly: Make sure to water your plants regularly, especially during hot, dry weather. Most plants need about 1 inch of water per week. Choose edible plants: Since you're interested in growing edible plants, here are three suggestions that do well in Seattle's climate: Tomatoes: Tomatoes are easy to grow and come in a variety of sizes and colors. They do best in full sun and need support as they grow. Cherry tomatoes are a good option for small spaces. Peppers: Peppers come in many varieties and are also easy to grow. They do well in pots and need full sun. You can use them fresh or dry them for later use. Herbs: Herbs like basil, thyme, and oregano are easy to grow and can be used in cooking. They do well in pots and can be grown indoors or outdoors. Remember to do your research on the specific needs of the plants you choose, and don't be afraid to ask for advice from your local garden center or other experienced gardeners in your area. Good luck with your garden!");
    }

    // // Handles any errors that might occurr
    // @ExceptionHandler({ CustomException1.class, CustomException2.class })
    // public void handleException() {
    //     //
    // }

}